// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRn9FHjujPn6xsQHachQpH4VmeQl-B_Bg',
    appId: '1:902950254348:web:278623c93b20093c65bb29',
    messagingSenderId: '902950254348',
    projectId: 'sampledesu-e71ad',
    authDomain: 'sampledesu-e71ad.firebaseapp.com',
    storageBucket: 'sampledesu-e71ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtIUU9U_v0ILtqZ7JmBQHqalBLRjuvxc0',
    appId: '1:902950254348:android:eb2a0c73e8d54a5265bb29',
    messagingSenderId: '902950254348',
    projectId: 'sampledesu-e71ad',
    storageBucket: 'sampledesu-e71ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnoQkYu4wKg9bOSdoilTQYU68ie2LQ-4A',
    appId: '1:902950254348:ios:4d4724e51c376ec065bb29',
    messagingSenderId: '902950254348',
    projectId: 'sampledesu-e71ad',
    storageBucket: 'sampledesu-e71ad.appspot.com',
    iosClientId: '902950254348-9q5i55eultnf7io4lq2vik0l8pgp1oqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnoQkYu4wKg9bOSdoilTQYU68ie2LQ-4A',
    appId: '1:902950254348:ios:4d4724e51c376ec065bb29',
    messagingSenderId: '902950254348',
    projectId: 'sampledesu-e71ad',
    storageBucket: 'sampledesu-e71ad.appspot.com',
    iosClientId: '902950254348-9q5i55eultnf7io4lq2vik0l8pgp1oqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice',
  );
}
